version: "3.7"
services:
  app:
    image: ghcr.io/antonalexeevusa/oled-stats:1.1.1
    restart: on-failure
    devices:
      - /dev/i2c-1
      - /dev/gpiochip0
      - /dev/nvme0
      - /dev/nvme0n1
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
