version: "3.7"
services:
  app:
    image: ghcr.io/antonalexeevusa/oled-stats:1.2.0
    restart: on-failure
    environment:
      CPU_POLL_INTERVAL: "60"
      RAM_POLL_INTERVAL: "60"
      SSD_POLL_INTERVAL: "300"
    devices:
      - /dev/i2c-1
      - /dev/gpiochip0
      - /dev/nvme0
      - /dev/nvme0n1
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
